market_buy_and_limit_sell:
  name: Market buy and limit sell
  description: Create a market buy order with a buy_percentage of the available free quote currency. Then, sell this amount for a certain profit.
  fields:
    symbol:
      name: Symbol
      description: The symbol on which to create orders.
      required: true
      selector:
        text:
    buy_percentage:
      name: Buy Percentage
      description: The amount to buy as a percentage of the available free quote currency. 
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    sell_profit:
      name: Sell Profit
      description: The sell price as a profit percentage of the buy price.
      required: true
      selector:
        number:
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider